services:
  # Ubuntu 20.04 test environment
  ubuntu20-04:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.ubuntu20-04
    container_name: env-script-ubuntu20
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
    environment:
      - TEST_ENV=docker
      - DEBIAN_FRONTEND=noninteractive
    command: ["/app/tools/test-runner.sh", "--all"]

  # Ubuntu 22.04 test environment
  ubuntu22-04:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.ubuntu22-04
    container_name: env-script-ubuntu22
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
    environment:
      - TEST_ENV=docker
      - DEBIAN_FRONTEND=noninteractive
    command: ["/app/tools/test-runner.sh", "--all"]

  # Ubuntu 24.04 test environment
  ubuntu24-04:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.ubuntu24-04
    container_name: env-script-ubuntu24
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
    environment:
      - TEST_ENV=docker
      - DEBIAN_FRONTEND=noninteractive
    command: ["/app/tools/test-runner.sh", "--all"]

  # Debian 11.9 Bullseye test environment
  debian11-9:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.debian11-9
    container_name: env-script-debian11-9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
    environment:
      - TEST_ENV=docker
      - DEBIAN_FRONTEND=noninteractive
    command: ["/app/tools/test-runner.sh", "--all"]

  # Debian 12.2 Bookworm test environment
  debian12-2:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.debian12-2
    container_name: env-script-debian12-2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
    environment:
      - TEST_ENV=docker
      - DEBIAN_FRONTEND=noninteractive
    command: ["/app/tools/test-runner.sh", "--all"]

  # Fedora 41 test environment
  fedora41:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.fedora41
    container_name: env-script-fedora41
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
    environment:
      - TEST_ENV=docker
    command: ["/app/tools/test-runner.sh", "--all"]

  # RedHat Enterprise Linux 8.10 (UBI8) test environment
  redhat8-10:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.redhat8-10
    container_name: env-script-redhat8-10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
    environment:
      - TEST_ENV=docker
    command: ["/app/tools/test-runner.sh", "--all"]

  # RedHat Enterprise Linux 9.6 (UBI9) test environment
  redhat9-6:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.redhat9-6
    container_name: env-script-redhat9-6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
    environment:
      - TEST_ENV=docker
    command: ["/app/tools/test-runner.sh", "--all"]

  # Ubuntu 20.04 with Docker CE and Docker Compose
  ubuntu20-04-docker:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.ubuntu20-04.docker
    container_name: env-script-ubuntu20-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
    environment:
      - TEST_ENV=docker
      - DEBIAN_FRONTEND=noninteractive
    privileged: true
    command: ["/app/tools/test-runner.sh", "--all"]

  # Ubuntu 22.04 with Docker CE and Docker Compose
  ubuntu22-04-docker:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.ubuntu22-04.docker
    container_name: env-script-ubuntu22-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
    environment:
      - TEST_ENV=docker
      - DEBIAN_FRONTEND=noninteractive
    privileged: true
    command: ["/app/tools/test-runner.sh", "--all"]

  # Ubuntu 24.04 with Docker CE and Docker Compose
  ubuntu24-04-docker:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.ubuntu24-04.docker
    container_name: env-script-ubuntu24-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
    environment:
      - TEST_ENV=docker
      - DEBIAN_FRONTEND=noninteractive
    privileged: true
    command: ["/app/tools/test-runner.sh", "--all"]

  # Debian 11.9 Bullseye with Docker CE and Docker Compose
  debian11-9-docker:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.debian11-9.docker
    container_name: env-script-debian11-9-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
    environment:
      - TEST_ENV=docker
      - DEBIAN_FRONTEND=noninteractive
    privileged: true
    command: ["/app/tools/test-runner.sh", "--all"]

  # Debian 12.2 Bookworm with Docker CE and Docker Compose
  debian12-2-docker:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.debian12-2.docker
    container_name: env-script-debian12-2-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
    environment:
      - TEST_ENV=docker
      - DEBIAN_FRONTEND=noninteractive
    privileged: true
    command: ["/app/tools/test-runner.sh", "--all"]

  # Fedora 41 with Docker CE and Docker Compose
  fedora41-docker:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.fedora41.docker
    container_name: env-script-fedora41-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
    environment:
      - TEST_ENV=docker
    privileged: true
    command: ["/app/tools/test-runner.sh", "--all"]

  # RedHat Enterprise Linux 8.10 (UBI8) with Docker CE and Docker Compose
  redhat8-10-docker:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.redhat8-10.docker
    container_name: env-script-redhat8-10-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
    environment:
      - TEST_ENV=docker
    privileged: true
    command: ["/app/tools/test-runner.sh", "--all"]

  # RedHat Enterprise Linux 9.6 (UBI9) with Docker CE and Docker Compose
  redhat9-6-docker:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.redhat9-6.docker
    container_name: env-script-redhat9-6-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
    environment:
      - TEST_ENV=docker
    privileged: true
    command: ["/app/tools/test-runner.sh", "--all"]

  # Interactive test environment
  interactive:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.ubuntu22-04
    container_name: env-script-interactive
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
    environment:
      - TEST_ENV=docker
      - DEBIAN_FRONTEND=noninteractive
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
